---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)

```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Function get_info_data

```{r function-get_info_data}
#' get_info_data
#' 
#' The function will provide the following information about the data.frame: dimension and column names.
#'
#' @param mydata a data.frame  
#' @return a list with as first element the data.frame dimension and as second element the name of the columns
#' 
#' @export
#'
#' @examples
#' 
get_info_data <- function(mydata) {
  
stopifnot("mydata is not a data frame" = is.data.frame(mydata))
  
 dimension <- dim(mydata)
 names <- colnames(mydata)
 

   return(list(
     dimension = dimension, 
     names = names))
 
}
```

```{r examples-get_info_data}
get_info_data(iris)
get_info_data(my_dataset)

```

```{r tests-get_info_data}
test_that("get_info_data is a function", {
  expect_true(inherits(get_info_data, "function")) 
})

test_that("get_info_data error message works",
           {
             expect_error(get_info_data("mydata"), "mydata is not a data frame")
           })

test_that("get_info_data works",{
  
  output <- get_info_data(iris)
  
  expect_equal(
    object=output[["names"]],
    expected =(
     c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", 
"Species")
))
    }
)

test_that("get_info_data works",{
  
  output <- get_info_data(iris)
  
  expect_equal(
    object=output[["dimension"]],
    expected =(
     c(150L, 5L)
))
    }
)

```

# get_mean_data
    
```{r function-get_mean_data}
#' get_mean_data
#' 
#' get_mean_data will get a table with the average of all numeric variables in your data.frame as parameter.
#' 
#' @param mydata a data.frame
#' 
#' @return a table with the average of all numeric variables in the data.frame
#' 
#' @importFrom dplyr summarise across 
#' @importFrom tibble as_tibble
#' @importFrom tidyselect where
#' 
#' @export
#' 
get_mean_data <- function(mydata){
    
  stopifnot("mydata is not a data frame" = is.data.frame(mydata))
  
 result <-  mydata%>%
  as_tibble()%>%
summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))
  
 return(result) 
}
```
  
```{r example-get_mean_data}
get_mean_data(iris)
get_mean_data(my_dataset)
```
  
```{r tests-get_mean_data}
test_that("get_mean_data works", {
  expect_true(inherits(get_mean_data, "function")) 
})

test_that("get_mean_data error message works",
           {
             expect_error(get_mean_data("mydata"), "mydata is not a data frame")
           })

test_that("get_mean_data works",{
  
  output <- get_mean_data(iris)
  
  expect_equal(
    object=output,
    expected =(
      structure(
        list(
          Sepal.Length = 5.84333333333333,
          Sepal.Width = 3.05733333333333,
          Petal.Length = 3.758,
          Petal.Width = 1.19933333333333
        ),
        class = c("tbl_df",
                  "tbl", "data.frame"),
        row.names = c(NA, -1L)
      )
))
    }
)

```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "Minimal")
```
