# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_mean_data works", {
  expect_true(inherits(get_mean_data, "function")) 
})

test_that("get_mean_data error message works",
           {
             expect_error(get_mean_data("mydata"), "mydata is not a data frame")
           })

test_that("get_mean_data error message works",
           {
             df <- dplyr::starwars%>% dplyr::select(name,hair_color) 
             
             expect_error(get_mean_data(df), "mydata must at least contain one numeric column!")
           })

test_that("get_mean_data works",{
  
  output <- get_mean_data(iris)
  
  expect_equal(
    object=output,
    expected =(
      structure(
        list(
          Sepal.Length = 5.84333333333333,
          Sepal.Width = 3.05733333333333,
          Petal.Length = 3.758,
          Petal.Width = 1.19933333333333
        ),
        class = c("tbl_df",
                  "tbl", "data.frame"),
        row.names = c(NA, -1L)
      )
))
    }
)

