# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_info_data is a function", {
  expect_true(inherits(get_info_data, "function")) 
})

test_that("get_info_data error message works",
           {
             expect_error(get_info_data("mydata"), "mydata is not a data frame")
           })

test_that("get_info_data works",{
  
  output <- get_info_data(iris)
  
  expect_equal(
    object=output[["names"]],
    expected =(
     c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", 
"Species")
))
    }
)

test_that("get_info_data works",{
  
  output <- get_info_data(iris)
  
  expect_equal(
    object=output[["dimension"]],
    expected =(
     c(150L, 5L)
))
    }
)

