# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' get_info_data
#' 
#' The function will provide the following information about the data.frame: dimension and column names.
#'
#' @param mydata a data.frame  
#' @return a list with as first element the data.frame dimension and as second element the name of the columns
#' 
#' @export
#'
#' @examples
#' 
#' get_info_data(iris)
#' get_info_data(my_dataset)
#' 
get_info_data <- function(mydata) {
  
stopifnot("mydata is not a data frame" = is.data.frame(mydata))
  
 dimension <- dim(mydata)
 names <- colnames(mydata)
 

   return(list(
     dimension = dimension, 
     names = names))
 
}
