# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' get_mean_data
#' 
#' get_mean_data will get a table with the average of all numeric variables in your data.frame as parameter.
#' 
#' @param mydata a data.frame
#' 
#' @return a table with the average of all numeric variables in the data.frame
#' 
#' @importFrom dplyr summarise across 
#' @importFrom tibble as_tibble
#' @importFrom tidyselect where
#' 
#' @export
#' 
#' @examples
#' get_mean_data(iris)
#' get_mean_data(my_dataset)
get_mean_data <- function(mydata){
    
  stopifnot("mydata is not a data frame" = is.data.frame(mydata))
  
 result <-  mydata%>%
  as_tibble()%>%
summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))
  
 return(result) 
}
